language: python

cache: pip

dist: trusty

addons:
  apt:
    packages:
      - libxml2-dev
      - libxslt1-dev

jobs:
  include:
    - stage: unit-test
      python: "2.7"
      env: TOXENV=py27
      install: pip install codecov tox
      script: tox -- --exitfirst -m unit
      after_success: codecov --disable search --flags unittests

    - stage: unit-test
      python: "3.5"
      env: TOXENV=py35
      install: pip install codecov tox
      script: tox -- --exitfirst -m unit
      after_success: codecov --disable search --flags unittests

    - stage: integration-test
      python: "2.7"
      env: TOXENV=py27
      install: pip install codecov tox
      script: tox -- --exitfirst -m integration
      after_success: codecov --disable search --flags integrationtests

    - stage: integration-test
      python: "3.5"
      env: TOXENV=py35
      install: pip install codecov tox
      script: tox -- --exitfirst -m integration
      after_success: codecov --disable search --flags integrationtests
