language: python

cache: pip

dist: trusty

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.5"
      env: TOXENV=py35

addons:
  apt:
    packages:
      - libxml2-dev
      - libxslt1-dev

before_install:
  - pip install codecov

install:
  - pip install tox

script:
  - tox

after_success:
  - tox -e coverage-report
  - codecov
