language: python

cache: pip

dist: trusty

python:
  - "3.5"

addons:
  apt:
    packages:
      - libxml2-dev
      - libxslt1-dev

install:
  - pip install --requirement requirements/dev.txt
  - pip install .

script:
  - py.test -m unit --cov pyfes --exitfirst
